### ISSUE TITLE
While Performing Purchase Request on Nexus 5  i get this Error - any idea?

### ISSUE THREAD

**Issue by haroonabbasi** [appcelerator-archive/ti.inappbilling#17]
07-21 17:48:33.507: E/PhoneInterfaceManager(1730): [PhoneIntfMgr] getIccId: No UICC
07-21 16:36:10.674: E/Volley(30266): [964] c.a: Unexpected response code 403 for https://android.clients.google.com/fdfe/ees/preparePurchase

Along with msg on screen "Authentication is required. You need to sign into your google Account"

**Comment by natefollmer** [comment]
Sounds to me like there's no Google Account sign in inside the Play Store?

**Comment by haroonabbasi** [comment]
The account was logged in play store.

some how issue got fixed not sure how, but it fixed.

**Comment by zszen** [comment]
same problem. Have you fixed it yet ?

**Comment by haroonabbasi** [comment]
@zszen i am sure exactly how it got fixed as it been almost a year, but i think couple of things you can make sure.

Test it with google account which has credit card setup
And the test account should be added as test user as well.
