### ISSUE TITLE
Appceleretator sdk 7.0.1 support?

### ISSUE THREAD

**Issue by ottopic** [appcelerator-archive/ti.inappbilling#28]
Does it will support 7.0.1 sdk? If not, what's the way to implement android's in-app-purchase?

**Comment by hansemannn** [comment]
It supports Titanium SDK 7+, but I think the release page hasn't been updated with the new release so far. Just done that, have fun!

**Comment by ottopic** [comment]
Thanks, you are the best!

**Comment by ottopic** [comment]
Sorry @hansemannn , it isn't compiled. Can you explain me how do it? Or, can you link me a valid guide?

Best regards

**Comment by hansemannn** [comment]
Added the binary.
