### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jamesboyle1968** [appcelerator-archive/ti.inappbilling#31]
I am bit of a newbie but I am sure this module does not work with Appcelerator and SDK 7.1. Keeps on giving me a error on the device screen whenever I try to buy something. Checked my google play configuration - all seems fine, using an actual phone as well. Just does not seem to work.

**Comment by nigelunderwood** [comment]
I have the same issue in that the module does not work with 7.1 SDK. Apparently we have to wait for 7.2 SDK which is not good for me as I have to finish the app dev work. Trying to port back to 6.X SDK, but this version I find far too buggy so at the moment I have heading to a dead end.

**Comment by jamesboyle1968** [comment]
Why do we have to wait....cant this be fixed to work with 7.1, I mean it says it works but from what I have tried and what you say also, it clearly does not work.

**Comment by hansemannn** [comment]
Guys, this is an archived module with being open source for anyone to contribute. If you need it today, you can simply patch your SDK with [this pull request](https://github.com/appcelerator/titanium_mobile/pull/9930) by @garymathews or apply the libraries manually using Gradle / by copying the files into your project.

**Comment by jamesboyle1968** [comment]
Thank you for the information and the suggestion. I have tried clicking on the link https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9930/8/artifact/dist/mobilesdk-7.2.0.v20180314152013-osx.zip in the pull request but I do not have access to download this - gives me some read/write error.

**Comment by hansemannn** [comment]
The Jenkins artifacts are internal only (QE-team). You can use Git to clone this PR into the 7_1_X branch, which is effectively the 7.1.0.GA.

**Comment by jamesboyle1968** [comment]
I worked all night trying to get this to work and whilst I got it to compile, I just end up with an error of 

java.lang.NoSuchFieldError: No static field AppCompatTheme_viewInflaterClass of type I

when the app starts. Can someone not just provide a download as this is all beyond my knowledge and dont know what I am going to say to my client now.

**Comment by hansemannn** [comment]
Is this only happening with 7.1.0? If so, you could just downgrade to 7.0.x and wait for the next release. Otherwise, if you have a pro or enterprise shbscription, you might want to get in touch with support to prioritize the fix. I‘ll also try a few more things today, but it doesn‘t have a blocker priority right now.

**Comment by jamesboyle1968** [comment]
Had to get some sleep after the overnighter. I have tried this on 7.0.X and 7.1.0, same error - found out I can look at adb log and I see this error

java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater

**Comment by jamesboyle1968** [comment]
Pretty much tried everything, even downgrading to SDK 5 and still the same java.lang.ClassNotFoundException

**Comment by hansemannn** [comment]
It looks like Google now requires it internally. The above mentioned PR will fix it for sure, so I may need to compile it for you guys ...

**Comment by jamesboyle1968** [comment]
Recompiling is beyond me, so if you can do this that would be cool and mean I won't need another overnighter stabbing in the dark

**Comment by hansemannn** [comment]
I cherry-picked the commit into [this branch](https://github.com/hansemannn/titanium_mobile/tree/7_1_X-support-libs). Compiling now ...

Please note that you will also need to have SDK level 27 installed, either via Android Studio (recommended) or CLI: `<android-sdk-dir>/tools/bin/sdkmanager "platforms;android-27"`

**Comment by hansemannn** [comment]
New module (5.1.0, requires the 7.1.1 custom build): [Download](https://www.dropbox.com/s/dvodwa0l68esiz5/ti.inappbilling-android-5.1.0.zip?dl=1)
7.1.1 build (7.1.0.GA + the above pull request): [Download](https://www.dropbox.com/s/h8ym6nn81htxvgr/mobilesdk-7.1.1-osx.zip?dl=0)

**Comment by jamesboyle1968** [comment]
Thanks man, you are a life saver!

**Comment by nigelunderwood** [comment]
I will second that one for sure, thanks a bunch!

**Comment by jamesboyle1968** [comment]
Removed all SDK's so only level 27 is present and then built using SDK7.1.1 and inappbilling module 5.1.1 and I got the same error as before

java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater

What has google done to blow this all up!

**Comment by hansemannn** [comment]
Really weird. I‘ll give it another shot tomorrow!

**Comment by jamesboyle1968** [comment]
Can't say thanks enough for this.

**Comment by hansemannn** [comment]
Try [this module](https://www.dropbox.com/s/dvodwa0l68esiz5/ti.inappbilling-android-5.1.0.zip?dl=1) which is fixed via packaging support library v13 like described [here](https://stackoverflow.com/questions/32300142/java-lang-noclassdeffounderror-android-support-v7-widget-since-upgrading-to-s).

**Comment by jamesboyle1968** [comment]
I cleaned the project and rebuilt, tried several times to make sure as the build throws an exception of

Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/app/ActionBarDrawerToggle;

Listing a bunch of classes

**Comment by hansemannn** [comment]
Yeah, I expected that..Now you have two different support libraries bundled.

**Comment by jamesboyle1968** [comment]
Is there anything that can be done to resolve this - tried a few things and continues to crash out

**Comment by nigelunderwood** [comment]
James - have you got anywhere with this? Interestingly, I think its a fault in this module rather than Appcelerator support libraries. I installed a games app with inapp purchases, run adb logcat and attempted to make a purchase. Well, the following came on the console from this games app

03-30 00:13:11.962 19694 19694 I AppCompatDelegate: Failed to instantiate custom view inflater android.support.v7.app.AppCompatViewInflater. Falling back to default.
03-30 00:13:11.962 19694 19694 I AppCompatDelegate: java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater

And then the inapp purchase screen was displayed, so this must mean an exception is not being handled correctly in this ti.inappbilling module.

**Comment by jamesboyle1968** [comment]
No man, no luck at all. Certainly interesting what you have found. I have looked into the AppCompatViewInflater and this is for backwards look and feel prior to KitkKat. So the fact that it is saying "Falling back to default", could it be that the module is ignoring the app theme and as such it has nothing to fall back on - this could make sense.

**Comment by nigelunderwood** [comment]
Ok this whole ClassNotFoundException is a complete distraction, this is perfectly fine as it means the device does not have inbuilt UI support for backwards compatibility - so we can ignore this as Android deals with it. I have this module working and one must follow exactly the Google Play setup for InApp Purchase testing 

https://developer.android.com/google/play/billing/billing_testing.html

if you follow this guide it will work fine. No Support Library update is required, works perfectly fine with SDK 7.1.0.

**Comment by jamesboyle1968** [comment]
Well done dude, had basically given up on this !!! I've read the guide and I see where I am going wrong now. Cheers man, life saver.
