### ISSUE TITLE
java.lang.IllegalStateException: Setup already completed.

### ISSUE THREAD

**Issue by andersdp** [appcelerator-archive/ti.inappbilling#32]
I get this error the second time I want to open my window with in-app products.
`java.lang.IllegalStateException: Setup already completed.`

I run
`InAppBilling.startSetup({publicKey: PUBLIC_KEY});`
in my constructor when opening the window via 
`Alloy.createController('creditsAndroid').open();`

Do I need to call a close method on the module? Although there is none to found - what am I missing?

SDK 7.1.1

**Comment by nigelunderwood** [comment]
You only need to do this once in your app. Add in your app.js and then you will be fine.

**Comment by andersdp** [comment]
Ok, thanks. Simple enough :)

But lets say something went wrong and I want to test if setup has been done when I open my purchase window - can I do that?
