### ISSUE TITLE
Failing on Newer Samsung Devices (S5, S6, Note Edge)

### ISSUE THREAD

**Issue by Geek-Fish** [appcelerator-archive/ti.inappbilling#9]
I don't have access to any of these devices at the moment, but I've been getting a flurry of people who cannot purchase or restore purchases on newer Samsung devices. The biggest culprit has been the S5. 

2 questions:

1. Has this module been abandoned?  (kind of random, but thought I'd ask)
2. Has anybody seen this issue and have they gotten an error that I can work with to track this down?

**Comment by annakozy2011** [comment]
We have a report from 1 user that she cannot purchase on Galaxy S4. Is it a newer device? 

Our (or maybe google's) waiting indicator never disappears, which may mean that InAppBilling.purchase freezes... is it related?

**Comment by Geek-Fish** [comment]
Sorry @annakozy2011 just saw this. The few people I've gotten to try and help with the issue state that nothing happens at all when they click buy now in our app ( the play store pop up never shows). I can't reproduce on any of my phones. Works fine on my old Note 3 too.

**Comment by natefollmer** [comment]
Well I have a little more info on this (for restoring anyway). Even following the example, on some Samsung devices, e.inventory comes back as undefined. Works fine on my Samsung S5 I purchased for testing, as well as all of my other phones, but some people are still getting this error. Any ideas what could be causing e.inventory to come back undefined after  queryinventorycomplete?

**Comment by natefollmer** [comment]
Seems I'm getting a responseCode 5 back from Google when trying to restore... Odd, purchasing works ok.
